model:
  type: GraphDiffusion
  node_dim: 128
  edge_dim: 64
  hidden_dim: 256
  num_layers: 6
  dropout: 0.1

training:
  batch_size: 8
  learning_rate: 1.0e-4
  num_epochs: 5
  scheduler: cosine
  gradient_clip: 1.0
  save_every: 10
  validate_every: 5

data:
  dataset: zinc15
  max_nodes: 20
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  num_workers: 4

generation:
  num_samples: 100
  max_nodes: 20
  temperature: 1.0
  batch_size: 64

constraints:
  lipinski: true
  qed_threshold: 0.5
  logp_range:
  - -2
  - 5
  mw_range:
  - 150
  - 500

evaluation:
  metrics:
  - validity
  - uniqueness
  - novelty
  - qed
  - lipinski
  reference_dataset: zinc15
  num_reference: 10000

logging:
  level: INFO
  use_wandb: false
  use_tensorboard: true
  log_dir: logs